#!/bin/bash                                                                      

set -e                                                                           

prevHEAD=$1                                                                      
newHEAD=$2                                                                       
checkoutType=$3                                                                  

dir=$(dirname $0)
sh $dir/update-mvn-conf
