#!/bin/bash                                                                      

set -e                                                                           

MVN_CONF=.mvn/maven.config

mkdir -p ./.mvn

VER=$(cat .mvn/version)
BRANCH_ABBR=$(git rev-parse --abbrev-ref HEAD | sed -e 's/^/_/' | sed -r -e "s/(feature\/|_?develop|_?master)//g" | sed "s/-/_/g" | sed -r -e "s/^[_-]?HEAD//g" | (tr -d '\n' && echo "-SNAPSHOT") )

# blank sha1 for local dev

cat << EOF > $MVN_CONF
-Drevision=$VER
-Dsha1=
-Dchangelist=$BRANCH_ABBR
EOF

