version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "no.nav.teamdokumenthandtering:teamdokumenthandtering-avro-schemas"
    groups:
      prod-deps:
        dependency-type: "production"
        exclude-patterns:
          - "no.nav.*"
      dev-deps:
        dependency-type: "development"
        exclude-patterns:
          - "no.nav.*"
      interne-deps:
        patterns:
          - "no.nav.*"
