openapi: 3.0.1
info:
  title: DistribuerJournalpost API
  description: 'Her dokumenteres tjenestegrensesnittet til distribuerJournalpost.
    Til autentisering brukes OIDC-token (JWT via OAuth2.0). Følgende format må brukes
    i Authorize sitt input-felt "Value": <strong> Bearer {token} </strong>. Eksempel
    på verdi i input-feltet: <strong> Bearer eYdmifml0ejugm </strong>. Et gyldig token
    kommer til å ha mange flere karakterer enn i eksempelet.'
  contact:
    name: Team Dokument
  license: {}
  version: 0.0.0
servers:
  - url: //dokdistfordeling-q2.nais.preprod.local/
tags:
  - name: distribuerJournalpost API
    description: Tilbyr distribusjon av journalposter
paths:
  /rest/v1/distribuerjournalpost:
    post:
      tags:
        - distribuerJournalpost API
      summary: Bestiller distribusjon av en journalpost.
      operationId: distribuerJournalpostUsingPOST
      parameters:
        - name: Nav-CallId
          in: header
          description: Nav-CallId - teknisk sporingsid
          schema:
            type: string
        - name: Nav-Consumer-Id
          in: header
          description: Nav-Consumer-Id - teknisk sporingsinfo om konsument
          schema:
            type: string
      requestBody:
        description: distribuerJournalpostRequestTo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DistribuerJournalpostRequestTo model'
        required: true
      responses:
        200:
          description: OK - journalposten distribueres og bestillingsId returneres.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DistribuerJournalpostRequestTo model'
        400:
          description: Ugyldig input. Validering av request body, eller validering
            av journalposten som journalpostId refererer til feilet.
          content: {}
        401:
          description: |-
            * Bruker mangler tilgang for å vise journalposten.
            * Ugyldig OIDC token.
          content: {}
        404:
          description: Journalposten ble ikke funnet.
          content: {}
        500:
          description: ' Teknisk feil under prosessering av forsendelse.'
          content: {}
      deprecated: false
      security:
        - apiKey: []
      x-codegen-request-body-name: distribuerJournalpostRequestTo
components:
  schemas:
    AdresseTo:
      title: AdresseTo
      type: object
      properties:
        adressetype:
          type: string
          description: '"norskPostadresse" eller "utenlandskPostadresse"'
          example: norskPostadresse
        postnummer:
          type: string
          description: Påkrevd hvis adressetype = "norskPostadresse"
          example: "0505"
        poststed:
          type: string
          description: Påkrevd hvis adressetype = "norskPostadresse"
          example: Oslo
        adresselinje1:
          type: string
          description: Påkrevd hvis adressetype = "utenlandskPostadresse"
          example: Eksempelveien 11B
        adresselinje2:
          type: string
          description: Alternativ postadresse 2
          example: Eksempelveien 12B
        adresselinje3:
          type: string
          description: Alternativ postadresse 3
          example: Eksempelveien 13B
        land:
          type: string
          description: To-bokstavers landkode ihht iso3166-1 alfa-2
          example: NO
    DistribuerJournalpostRequestTo model:
      title: DistribuerJournalpostRequestTo model
      type: object
      properties:
        journalpostId:
          type: string
          description: Journalpost som skal distribueres
          example: "343752389"
        batchId:
          type: string
          description: Identifiserer batch som forsendelsen inngår i. Lar bestiller
            identifisere forsendelser som hører sammen. Fritekst, og konsument må
            selv vurdere hva som er hensiktsmessige verdier
          example: "54321"
        bestillendeFagsystem:
          type: string
          description: Fagsystemet som bestiller distribusjon
          example: SYM
        adresse:
          $ref: '#/components/schemas/AdresseTo'
        dokumentProdApp:
          type: string
          description: Applikasjon som har produsert hoveddokumentet (for sporing
            og feilsøking)
          example: ELIN_STANDARD
    DistribuerJournalpostResponseTo model:
      title: DistribuerJournalpostResponseTo model
      type: object
      properties:
        bestillingsId:
          type: string
          description: |
            GUID generert av tjenesten som unikt identifiserer distribusjonsbestillingen
          example: 3ea4d118-6012-4fd0-9095-0f9944568d03
  securitySchemes:
    apiKey:
      type: apiKey
      name: Authorization
      in: header
