package no.nav.tjeneste.virksomhet.sak.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import no.nav.tjeneste.virksomhet.sak.v1.binding.FinnSakForMangeForekomster;
import no.nav.tjeneste.virksomhet.sak.v1.binding.FinnSakUgyldigInput;
import no.nav.tjeneste.virksomhet.sak.v1.binding.HentSakSakIkkeFunnet;
import no.nav.tjeneste.virksomhet.sak.v1.binding.SakV1;
import no.nav.tjeneste.virksomhet.sak.v1.meldinger.FinnSakRequest;
import no.nav.tjeneste.virksomhet.sak.v1.meldinger.FinnSakResponse;
import no.nav.tjeneste.virksomhet.sak.v1.meldinger.HentSakRequest;
import no.nav.tjeneste.virksomhet.sak.v1.meldinger.HentSakResponse;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Sak_v1", targetNamespace = "http://nav.no/tjeneste/virksomhet/sak/v1")
public class SakServiceMockImpl implements SakV1 {


    /**
     * 
     * @param request
     * @return
     *     returns no.nav.tjeneste.virksomhet.sak.v1.meldinger.FinnSakResponse
     * @throws FinnSakUgyldigInput
     * @throws FinnSakForMangeForekomster
     */
    @Override
    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/sak/v1/Sak_v1/finnSakRequest")
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "finnSak", targetNamespace = "http://nav.no/tjeneste/virksomhet/sak/v1", className = "no.nav.tjeneste.virksomhet.sak.v1.FinnSak")
    @ResponseWrapper(localName = "finnSakResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/sak/v1", className = "no.nav.tjeneste.virksomhet.sak.v1.FinnSakResponse")
    public FinnSakResponse finnSak(
        @WebParam(name = "request", targetNamespace = "")
        FinnSakRequest request)
        throws FinnSakForMangeForekomster, FinnSakUgyldigInput {
        FinnSakResponse response = new FinnSakResponse();
        return response;
    }

    /**
     * 
     * @param request
     * @return
     *     returns no.nav.tjeneste.virksomhet.sak.v1.meldinger.HentSakResponse
     * @throws HentSakSakIkkeFunnet
     */
    @Override
    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/sak/v1/Sak_v1/hentSakRequest")
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "hentSak", targetNamespace = "http://nav.no/tjeneste/virksomhet/sak/v1", className = "no.nav.tjeneste.virksomhet.sak.v1.HentSak")
    @ResponseWrapper(localName = "hentSakResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/sak/v1", className = "no.nav.tjeneste.virksomhet.sak.v1.HentSakResponse")
    public HentSakResponse hentSak(
        @WebParam(name = "request", targetNamespace = "")
        HentSakRequest request)
        throws HentSakSakIkkeFunnet {
        HentSakResponse response = new HentSakResponse();
        return response;
        
    }

    /**
     * 
     */
    @Override
    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/sak/v1/Sak_v1/pingRequest")
    @RequestWrapper(localName = "ping", targetNamespace = "http://nav.no/tjeneste/virksomhet/sak/v1", className = "no.nav.tjeneste.virksomhet.sak.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/sak/v1", className = "no.nav.tjeneste.virksomhet.sak.v1.PingResponse")
    public void ping() {
    }

}
