package no.nav.tps.proxy.api.v1.innsyn.dto;

/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om boadresse
 */
@ApiModel(description = "Informasjon om boadresse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Boadresse   {
    @JsonProperty("adresse")
    private String adresse = null;

    @JsonProperty("adressetillegg")
    private String adressetillegg = null;

    @JsonProperty("bydel")
    private String bydel = null;

    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("kommune")
    private String kommune = null;

    @JsonProperty("landkode")
    private String landkode = null;

    @JsonProperty("matrikkeladresse")
    private Matrikkeladresse matrikkeladresse = null;

    @JsonProperty("postnummer")
    private String postnummer = null;

    @JsonProperty("veiadresse")
    private Veiadresse veiadresse = null;

    public Boadresse adresse(String adresse) {
        this.adresse = adresse;
        return this;
    }

    /**
     * Primæradresse
     * @return adresse
     **/
    @JsonProperty("adresse")
    @ApiModelProperty(example = "TESTVEGEN 9110", value = "Primæradresse")
    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public Boadresse adressetillegg(String adressetillegg) {
        this.adressetillegg = adressetillegg;
        return this;
    }

    /**
     * Adressetillegg
     * @return adressetillegg
     **/
    @JsonProperty("adressetillegg")
    @ApiModelProperty(example = "TESTDALEN", value = "Adressetillegg")
    public String getAdressetillegg() {
        return adressetillegg;
    }

    public void setAdressetillegg(String adressetillegg) {
        this.adressetillegg = adressetillegg;
    }

    public Boadresse bydel(String bydel) {
        this.bydel = bydel;
        return this;
    }

    /**
     * Bydel
     * @return bydel
     **/
    @JsonProperty("bydel")
    @ApiModelProperty(example = "030929", value = "Bydel")
    public String getBydel() {
        return bydel;
    }

    public void setBydel(String bydel) {
        this.bydel = bydel;
    }

    public Boadresse datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public Boadresse kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public Boadresse kommune(String kommune) {
        this.kommune = kommune;
        return this;
    }

    /**
     * Kommune
     * @return kommune
     **/
    @JsonProperty("kommune")
    @ApiModelProperty(example = "0128", value = "Kommune")
    public String getKommune() {
        return kommune;
    }

    public void setKommune(String kommune) {
        this.kommune = kommune;
    }

    public Boadresse landkode(String landkode) {
        this.landkode = landkode;
        return this;
    }

    /**
     * Landkode
     * @return landkode
     **/
    @JsonProperty("landkode")
    @ApiModelProperty(example = "NOR", value = "Landkode")
    public String getLandkode() {
        return landkode;
    }

    public void setLandkode(String landkode) {
        this.landkode = landkode;
    }

    public Boadresse matrikkeladresse(Matrikkeladresse matrikkeladresse) {
        this.matrikkeladresse = matrikkeladresse;
        return this;
    }

    /**
     * Get matrikkeladresse
     * @return matrikkeladresse
     **/
    @JsonProperty("matrikkeladresse")
    @ApiModelProperty(value = "")
    public Matrikkeladresse getMatrikkeladresse() {
        return matrikkeladresse;
    }

    public void setMatrikkeladresse(Matrikkeladresse matrikkeladresse) {
        this.matrikkeladresse = matrikkeladresse;
    }

    public Boadresse postnummer(String postnummer) {
        this.postnummer = postnummer;
        return this;
    }

    /**
     * Postnummer
     * @return postnummer
     **/
    @JsonProperty("postnummer")
    @ApiModelProperty(example = "1892", value = "Postnummer")
    public String getPostnummer() {
        return postnummer;
    }

    public void setPostnummer(String postnummer) {
        this.postnummer = postnummer;
    }

    public Boadresse veiadresse(Veiadresse veiadresse) {
        this.veiadresse = veiadresse;
        return this;
    }

    /**
     * Get veiadresse
     * @return veiadresse
     **/
    @JsonProperty("veiadresse")
    @ApiModelProperty(value = "")
    public Veiadresse getVeiadresse() {
        return veiadresse;
    }

    public void setVeiadresse(Veiadresse veiadresse) {
        this.veiadresse = veiadresse;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Boadresse boadresse = (Boadresse) o;
        return Objects.equals(this.adresse, boadresse.adresse) &&
                Objects.equals(this.adressetillegg, boadresse.adressetillegg) &&
                Objects.equals(this.bydel, boadresse.bydel) &&
                Objects.equals(this.datoFraOgMed, boadresse.datoFraOgMed) &&
                Objects.equals(this.kilde, boadresse.kilde) &&
                Objects.equals(this.kommune, boadresse.kommune) &&
                Objects.equals(this.landkode, boadresse.landkode) &&
                Objects.equals(this.matrikkeladresse, boadresse.matrikkeladresse) &&
                Objects.equals(this.postnummer, boadresse.postnummer) &&
                Objects.equals(this.veiadresse, boadresse.veiadresse);
    }

    @Override
    public int hashCode() {
        return Objects.hash(adresse, adressetillegg, bydel, datoFraOgMed, kilde, kommune, landkode, matrikkeladresse, postnummer, veiadresse);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Boadresse {\n");

        sb.append("    adresse: ").append(toIndentedString(adresse)).append("\n");
        sb.append("    adressetillegg: ").append(toIndentedString(adressetillegg)).append("\n");
        sb.append("    bydel: ").append(toIndentedString(bydel)).append("\n");
        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    kommune: ").append(toIndentedString(kommune)).append("\n");
        sb.append("    landkode: ").append(toIndentedString(landkode)).append("\n");
        sb.append("    matrikkeladresse: ").append(toIndentedString(matrikkeladresse)).append("\n");
        sb.append("    postnummer: ").append(toIndentedString(postnummer)).append("\n");
        sb.append("    veiadresse: ").append(toIndentedString(veiadresse)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

