package no.nav.tps.proxy.api.v1.innsyn.dto;

/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informajson om egenansatt
 */
@ApiModel(description = "Informajson om egenansatt")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Egenansatt   {
    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("erEgenansatt")
    private Boolean erEgenansatt = null;

    @JsonProperty("kilde")
    private String kilde = null;

    public Egenansatt datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public Egenansatt erEgenansatt(Boolean erEgenansatt) {
        this.erEgenansatt = erEgenansatt;
        return this;
    }

    /**
     * Er person egenansatt
     * @return erEgenansatt
     **/
    @JsonProperty("erEgenansatt")
    @ApiModelProperty(example = "true", value = "Er person egenansatt")
    public Boolean isErEgenansatt() {
        return erEgenansatt;
    }

    public void setErEgenansatt(Boolean erEgenansatt) {
        this.erEgenansatt = erEgenansatt;
    }

    public Egenansatt kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Egenansatt egenansatt = (Egenansatt) o;
        return Objects.equals(this.datoFraOgMed, egenansatt.datoFraOgMed) &&
                Objects.equals(this.erEgenansatt, egenansatt.erEgenansatt) &&
                Objects.equals(this.kilde, egenansatt.kilde);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datoFraOgMed, erEgenansatt, kilde);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Egenansatt {\n");

        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    erEgenansatt: ").append(toIndentedString(erEgenansatt)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

