package no.nav.tps.proxy.api.v1.innsyn.dto;

/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om geografisk tilknytning
 */
@ApiModel(description = "Informasjon om geografisk tilknytning")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class GeografiskTilknytning   {
    @JsonProperty("bydel")
    private String bydel = null;

    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("kommune")
    private String kommune = null;

    @JsonProperty("land")
    private String land = null;

    public GeografiskTilknytning bydel(String bydel) {
        this.bydel = bydel;
        return this;
    }

    /**
     * Bydel
     * @return bydel
     **/
    @JsonProperty("bydel")
    @ApiModelProperty(example = "030119", value = "Bydel")
    public String getBydel() {
        return bydel;
    }

    public void setBydel(String bydel) {
        this.bydel = bydel;
    }

    public GeografiskTilknytning datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public GeografiskTilknytning kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public GeografiskTilknytning kommune(String kommune) {
        this.kommune = kommune;
        return this;
    }

    /**
     * Kommune
     * @return kommune
     **/
    @JsonProperty("kommune")
    @ApiModelProperty(example = "1824", value = "Kommune")
    public String getKommune() {
        return kommune;
    }

    public void setKommune(String kommune) {
        this.kommune = kommune;
    }

    public GeografiskTilknytning land(String land) {
        this.land = land;
        return this;
    }

    /**
     * Land
     * @return land
     **/
    @JsonProperty("land")
    @ApiModelProperty(example = "NOR", value = "Land")
    public String getLand() {
        return land;
    }

    public void setLand(String land) {
        this.land = land;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GeografiskTilknytning geografiskTilknytning = (GeografiskTilknytning) o;
        return Objects.equals(this.bydel, geografiskTilknytning.bydel) &&
                Objects.equals(this.datoFraOgMed, geografiskTilknytning.datoFraOgMed) &&
                Objects.equals(this.kilde, geografiskTilknytning.kilde) &&
                Objects.equals(this.kommune, geografiskTilknytning.kommune) &&
                Objects.equals(this.land, geografiskTilknytning.land);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bydel, datoFraOgMed, kilde, kommune, land);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GeografiskTilknytning {\n");

        sb.append("    bydel: ").append(toIndentedString(bydel)).append("\n");
        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    kommune: ").append(toIndentedString(kommune)).append("\n");
        sb.append("    land: ").append(toIndentedString(land)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

