package no.nav.tps.proxy.api.v1.innsyn.dto;

/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om innvandring og utvandring
 */
@ApiModel(description = "Informasjon om innvandring og utvandring")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class InnvandringUtvandring   {
    @JsonProperty("innvandretDato")
    private String innvandretDato = null;

    @JsonProperty("innvandretKilde")
    private String innvandretKilde = null;

    @JsonProperty("innvandretLand")
    private Kode innvandretLand = null;

    @JsonProperty("utvandretDato")
    private String utvandretDato = null;

    @JsonProperty("utvandretKilde")
    private String utvandretKilde = null;

    @JsonProperty("utvandretLand")
    private Kode utvandretLand = null;

    public InnvandringUtvandring innvandretDato(String innvandretDato) {
        this.innvandretDato = innvandretDato;
        return this;
    }

    /**
     * Dato innvandret, format (ISO-8601): yyyy-MM-dd
     * @return innvandretDato
     **/
    @JsonProperty("innvandretDato")
    @ApiModelProperty(example = "1981-12-12", value = "Dato innvandret, format (ISO-8601): yyyy-MM-dd")
    public String getInnvandretDato() {
        return innvandretDato;
    }

    public void setInnvandretDato(String innvandretDato) {
        this.innvandretDato = innvandretDato;
    }

    public InnvandringUtvandring innvandretKilde(String innvandretKilde) {
        this.innvandretKilde = innvandretKilde;
        return this;
    }

    /**
     * Fra hvor informasjonen er sendt fra
     * @return innvandretKilde
     **/
    @JsonProperty("innvandretKilde")
    @ApiModelProperty(value = "Fra hvor informasjonen er sendt fra")
    public String getInnvandretKilde() {
        return innvandretKilde;
    }

    public void setInnvandretKilde(String innvandretKilde) {
        this.innvandretKilde = innvandretKilde;
    }

    public InnvandringUtvandring innvandretLand(Kode innvandretLand) {
        this.innvandretLand = innvandretLand;
        return this;
    }

    /**
     * Get innvandretLand
     * @return innvandretLand
     **/
    @JsonProperty("innvandretLand")
    @ApiModelProperty(value = "")
    public Kode getInnvandretLand() {
        return innvandretLand;
    }

    public void setInnvandretLand(Kode innvandretLand) {
        this.innvandretLand = innvandretLand;
    }

    public InnvandringUtvandring utvandretDato(String utvandretDato) {
        this.utvandretDato = utvandretDato;
        return this;
    }

    /**
     * Dato utvandret, format (ISO-8601): yyyy-MM-dd
     * @return utvandretDato
     **/
    @JsonProperty("utvandretDato")
    @ApiModelProperty(example = "1994-09-01", value = "Dato utvandret, format (ISO-8601): yyyy-MM-dd")
    public String getUtvandretDato() {
        return utvandretDato;
    }

    public void setUtvandretDato(String utvandretDato) {
        this.utvandretDato = utvandretDato;
    }

    public InnvandringUtvandring utvandretKilde(String utvandretKilde) {
        this.utvandretKilde = utvandretKilde;
        return this;
    }

    /**
     * Fra hvor informasjonen er sendt fra
     * @return utvandretKilde
     **/
    @JsonProperty("utvandretKilde")
    @ApiModelProperty(value = "Fra hvor informasjonen er sendt fra")
    public String getUtvandretKilde() {
        return utvandretKilde;
    }

    public void setUtvandretKilde(String utvandretKilde) {
        this.utvandretKilde = utvandretKilde;
    }

    public InnvandringUtvandring utvandretLand(Kode utvandretLand) {
        this.utvandretLand = utvandretLand;
        return this;
    }

    /**
     * Get utvandretLand
     * @return utvandretLand
     **/
    @JsonProperty("utvandretLand")
    @ApiModelProperty(value = "")
    public Kode getUtvandretLand() {
        return utvandretLand;
    }

    public void setUtvandretLand(Kode utvandretLand) {
        this.utvandretLand = utvandretLand;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InnvandringUtvandring innvandringUtvandring = (InnvandringUtvandring) o;
        return Objects.equals(this.innvandretDato, innvandringUtvandring.innvandretDato) &&
                Objects.equals(this.innvandretKilde, innvandringUtvandring.innvandretKilde) &&
                Objects.equals(this.innvandretLand, innvandringUtvandring.innvandretLand) &&
                Objects.equals(this.utvandretDato, innvandringUtvandring.utvandretDato) &&
                Objects.equals(this.utvandretKilde, innvandringUtvandring.utvandretKilde) &&
                Objects.equals(this.utvandretLand, innvandringUtvandring.utvandretLand);
    }

    @Override
    public int hashCode() {
        return Objects.hash(innvandretDato, innvandretKilde, innvandretLand, utvandretDato, utvandretKilde, utvandretLand);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InnvandringUtvandring {\n");

        sb.append("    innvandretDato: ").append(toIndentedString(innvandretDato)).append("\n");
        sb.append("    innvandretKilde: ").append(toIndentedString(innvandretKilde)).append("\n");
        sb.append("    innvandretLand: ").append(toIndentedString(innvandretLand)).append("\n");
        sb.append("    utvandretDato: ").append(toIndentedString(utvandretDato)).append("\n");
        sb.append("    utvandretKilde: ").append(toIndentedString(utvandretKilde)).append("\n");
        sb.append("    utvandretLand: ").append(toIndentedString(utvandretLand)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

