package no.nav.tps.proxy.api.v1.innsyn.dto;
/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om kode i kodeverk
 */
@ApiModel(description = "Informasjon om kode i kodeverk")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Kode   {
    @JsonProperty("kodeverk")
    private String kodeverk = null;

    @JsonProperty("verdi")
    private String verdi = null;

    public Kode kodeverk(String kodeverk) {
        this.kodeverk = kodeverk;
        return this;
    }

    /**
     * Get kodeverk
     * @return kodeverk
     **/
    @JsonProperty("kodeverk")
    @ApiModelProperty(value = "")
    public String getKodeverk() {
        return kodeverk;
    }

    public void setKodeverk(String kodeverk) {
        this.kodeverk = kodeverk;
    }

    public Kode verdi(String verdi) {
        this.verdi = verdi;
        return this;
    }

    /**
     * Get verdi
     * @return verdi
     **/
    @JsonProperty("verdi")
    @ApiModelProperty(value = "")
    public String getVerdi() {
        return verdi;
    }

    public void setVerdi(String verdi) {
        this.verdi = verdi;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Kode kode = (Kode) o;
        return Objects.equals(this.kodeverk, kode.kodeverk) &&
                Objects.equals(this.verdi, kode.verdi);
    }

    @Override
    public int hashCode() {
        return Objects.hash(kodeverk, verdi);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Kode {\n");

        sb.append("    kodeverk: ").append(toIndentedString(kodeverk)).append("\n");
        sb.append("    verdi: ").append(toIndentedString(verdi)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

