package no.nav.tps.proxy.api.v1.innsyn.dto;

/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Informasjon om matrikkeladresse
 */
@ApiModel(description = "Informasjon om matrikkeladresse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Matrikkeladresse   {
    @JsonProperty("bruksnummer")
    private String bruksnummer = null;

    @JsonProperty("festenummer")
    private String festenummer = null;

    @JsonProperty("gaardsnummer")
    private String gaardsnummer = null;

    @JsonProperty("undernummer")
    private String undernummer = null;

    public Matrikkeladresse bruksnummer(String bruksnummer) {
        this.bruksnummer = bruksnummer;
        return this;
    }

    /**
     * Bruksnummer
     * @return bruksnummer
     **/
    @JsonProperty("bruksnummer")
    @ApiModelProperty(example = "0075", value = "Bruksnummer")
    public String getBruksnummer() {
        return bruksnummer;
    }

    public void setBruksnummer(String bruksnummer) {
        this.bruksnummer = bruksnummer;
    }

    public Matrikkeladresse festenummer(String festenummer) {
        this.festenummer = festenummer;
        return this;
    }

    /**
     * Get festenummer
     * @return festenummer
     **/
    @JsonProperty("festenummer")
    @ApiModelProperty(value = "")
    public String getFestenummer() {
        return festenummer;
    }

    public void setFestenummer(String festenummer) {
        this.festenummer = festenummer;
    }

    public Matrikkeladresse gaardsnummer(String gaardsnummer) {
        this.gaardsnummer = gaardsnummer;
        return this;
    }

    /**
     * Gårdsnummer
     * @return gaardsnummer
     **/
    @JsonProperty("gaardsnummer")
    @ApiModelProperty(example = "00055", value = "Gårdsnummer")
    public String getGaardsnummer() {
        return gaardsnummer;
    }

    public void setGaardsnummer(String gaardsnummer) {
        this.gaardsnummer = gaardsnummer;
    }

    public Matrikkeladresse undernummer(String undernummer) {
        this.undernummer = undernummer;
        return this;
    }

    /**
     * Undernummer
     * @return undernummer
     **/
    @JsonProperty("undernummer")
    @ApiModelProperty(example = "001", value = "Undernummer")
    public String getUndernummer() {
        return undernummer;
    }

    public void setUndernummer(String undernummer) {
        this.undernummer = undernummer;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Matrikkeladresse matrikkeladresse = (Matrikkeladresse) o;
        return Objects.equals(this.bruksnummer, matrikkeladresse.bruksnummer) &&
                Objects.equals(this.festenummer, matrikkeladresse.festenummer) &&
                Objects.equals(this.gaardsnummer, matrikkeladresse.gaardsnummer) &&
                Objects.equals(this.undernummer, matrikkeladresse.undernummer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bruksnummer, festenummer, gaardsnummer, undernummer);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Matrikkeladresse {\n");

        sb.append("    bruksnummer: ").append(toIndentedString(bruksnummer)).append("\n");
        sb.append("    festenummer: ").append(toIndentedString(festenummer)).append("\n");
        sb.append("    gaardsnummer: ").append(toIndentedString(gaardsnummer)).append("\n");
        sb.append("    undernummer: ").append(toIndentedString(undernummer)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

