package no.nav.tps.proxy.api.v1.innsyn.dto;
/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om navn
 */
@ApiModel(description = "Informasjon om navn")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Navn   {
    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("forkortetNavn")
    private String forkortetNavn = null;

    @JsonProperty("fornavn")
    private String fornavn = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("mellomnavn")
    private String mellomnavn = null;

    @JsonProperty("slektsnavn")
    private String slektsnavn = null;

    @JsonProperty("slektsnavnUgift")
    private String slektsnavnUgift = null;

    public Navn datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public Navn forkortetNavn(String forkortetNavn) {
        this.forkortetNavn = forkortetNavn;
        return this;
    }

    /**
     * Forkortet navn
     * @return forkortetNavn
     **/
    @JsonProperty("forkortetNavn")
    @ApiModelProperty(example = "Test Testte Testtest", value = "Forkortet navn")
    public String getForkortetNavn() {
        return forkortetNavn;
    }

    public void setForkortetNavn(String forkortetNavn) {
        this.forkortetNavn = forkortetNavn;
    }

    public Navn fornavn(String fornavn) {
        this.fornavn = fornavn;
        return this;
    }

    /**
     * Fornavn
     * @return fornavn
     **/
    @JsonProperty("fornavn")
    @ApiModelProperty(example = "Test Testte", value = "Fornavn")
    public String getFornavn() {
        return fornavn;
    }

    public void setFornavn(String fornavn) {
        this.fornavn = fornavn;
    }

    public Navn kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public Navn mellomnavn(String mellomnavn) {
        this.mellomnavn = mellomnavn;
        return this;
    }

    /**
     * Mellomnavn
     * @return mellomnavn
     **/
    @JsonProperty("mellomnavn")
    @ApiModelProperty(example = "Testte", value = "Mellomnavn")
    public String getMellomnavn() {
        return mellomnavn;
    }

    public void setMellomnavn(String mellomnavn) {
        this.mellomnavn = mellomnavn;
    }

    public Navn slektsnavn(String slektsnavn) {
        this.slektsnavn = slektsnavn;
        return this;
    }

    /**
     * Etternavn
     * @return slektsnavn
     **/
    @JsonProperty("slektsnavn")
    @ApiModelProperty(example = "Testtest", value = "Etternavn")
    public String getSlektsnavn() {
        return slektsnavn;
    }

    public void setSlektsnavn(String slektsnavn) {
        this.slektsnavn = slektsnavn;
    }

    public Navn slektsnavnUgift(String slektsnavnUgift) {
        this.slektsnavnUgift = slektsnavnUgift;
        return this;
    }

    /**
     * Sleksnavn ugift
     * @return slektsnavnUgift
     **/
    @JsonProperty("slektsnavnUgift")
    @ApiModelProperty(example = "Maskert", value = "Sleksnavn ugift")
    public String getSlektsnavnUgift() {
        return slektsnavnUgift;
    }

    public void setSlektsnavnUgift(String slektsnavnUgift) {
        this.slektsnavnUgift = slektsnavnUgift;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Navn navn = (Navn) o;
        return Objects.equals(this.datoFraOgMed, navn.datoFraOgMed) &&
                Objects.equals(this.forkortetNavn, navn.forkortetNavn) &&
                Objects.equals(this.fornavn, navn.fornavn) &&
                Objects.equals(this.kilde, navn.kilde) &&
                Objects.equals(this.mellomnavn, navn.mellomnavn) &&
                Objects.equals(this.slektsnavn, navn.slektsnavn) &&
                Objects.equals(this.slektsnavnUgift, navn.slektsnavnUgift);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datoFraOgMed, forkortetNavn, fornavn, kilde, mellomnavn, slektsnavn, slektsnavnUgift);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Navn {\n");

        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    forkortetNavn: ").append(toIndentedString(forkortetNavn)).append("\n");
        sb.append("    fornavn: ").append(toIndentedString(fornavn)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    mellomnavn: ").append(toIndentedString(mellomnavn)).append("\n");
        sb.append("    slektsnavn: ").append(toIndentedString(slektsnavn)).append("\n");
        sb.append("    slektsnavnUgift: ").append(toIndentedString(slektsnavnUgift)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

