package no.nav.tps.proxy.api.v1.innsyn.dto;

/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Objekt retunert fra relasjon, og barn-endepunktet
 */
@ApiModel(description = "Objekt retunert fra relasjon, og barn-endepunktet")
@Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Relasjon   {
    @JsonProperty("alder")
    private Integer alder = null;

    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("doedsdato")
    private Doedsdato doedsdato = null;

    @JsonProperty("egenansatt")
    private Egenansatt egenansatt = null;

    @JsonProperty("foedselsdato")
    private String foedselsdato = null;

    @JsonProperty("forkortetNavn")
    private String forkortetNavn = null;

    @JsonProperty("harSammeAdresse")
    private Boolean harSammeAdresse = null;

    @JsonProperty("ident")
    private String ident = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("kjoenn")
    private String kjoenn = null;

    @JsonProperty("relasjonsType")
    private Kode relasjonsType = null;

    @JsonProperty("spesiellOpplysning")
    private KodeMedDatoOgKilde spesiellOpplysning = null;

    @JsonProperty("statsborgerskap")
    private KodeMedDatoOgKilde statsborgerskap = null;

    private Relasjon(Builder builder) {
        setAlder(builder.alder);
        setDatoFraOgMed(builder.datoFraOgMed);
        setDoedsdato(builder.doedsdato);
        setEgenansatt(builder.egenansatt);
        setFoedselsdato(builder.foedselsdato);
        setForkortetNavn(builder.forkortetNavn);
        setHarSammeAdresse(builder.harSammeAdresse);
        setIdent(builder.ident);
        setKilde(builder.kilde);
        setKjoenn(builder.kjoenn);
        setRelasjonsType(builder.relasjonsType);
        setSpesiellOpplysning(builder.spesiellOpplysning);
        setStatsborgerskap(builder.statsborgerskap);
    }

    public Relasjon() {
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Relasjon copy) {
        Builder builder = new Builder();
        builder.alder = copy.getAlder();
        builder.datoFraOgMed = copy.getDatoFraOgMed();
        builder.doedsdato = copy.getDoedsdato();
        builder.egenansatt = copy.getEgenansatt();
        builder.foedselsdato = copy.getFoedselsdato();
        builder.forkortetNavn = copy.getForkortetNavn();
        builder.harSammeAdresse = copy.isHarSammeAdresse();
        builder.ident = copy.getIdent();
        builder.kilde = copy.getKilde();
        builder.kjoenn = copy.getKjoenn();
        builder.relasjonsType = copy.getRelasjonsType();
        builder.spesiellOpplysning = copy.getSpesiellOpplysning();
        builder.statsborgerskap = copy.getStatsborgerskap();
        return builder;
    }

    public Relasjon alder(Integer alder) {
        this.alder = alder;
        return this;
    }

    /**
     * Alder
     * @return alder
     **/
    @JsonProperty("alder")
    @ApiModelProperty(example = "19", value = "Alder")
    public Integer getAlder() {
        return alder;
    }

    public void setAlder(Integer alder) {
        this.alder = alder;
    }

    public Relasjon datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public Relasjon doedsdato(Doedsdato doedsdato) {
        this.doedsdato = doedsdato;
        return this;
    }

    /**
     * Get doedsdato
     * @return doedsdato
     **/
    @JsonProperty("doedsdato")
    @ApiModelProperty(value = "")
    public Doedsdato getDoedsdato() {
        return doedsdato;
    }

    public void setDoedsdato(Doedsdato doedsdato) {
        this.doedsdato = doedsdato;
    }

    public Relasjon egenansatt(Egenansatt egenansatt) {
        this.egenansatt = egenansatt;
        return this;
    }

    /**
     * Get egenansatt
     * @return egenansatt
     **/
    @JsonProperty("egenansatt")
    @ApiModelProperty(value = "")
    public Egenansatt getEgenansatt() {
        return egenansatt;
    }

    public void setEgenansatt(Egenansatt egenansatt) {
        this.egenansatt = egenansatt;
    }

    public Relasjon foedselsdato(String foedselsdato) {
        this.foedselsdato = foedselsdato;
        return this;
    }

    /**
     * Fødselsdato, format (ISO-8601): yyyy-MM-dd
     * @return foedselsdato
     **/
    @JsonProperty("foedselsdato")
    @ApiModelProperty(example = "2001-04-01", value = "Fødselsdato, format (ISO-8601): yyyy-MM-dd")
    public String getFoedselsdato() {
        return foedselsdato;
    }

    public void setFoedselsdato(String foedselsdato) {
        this.foedselsdato = foedselsdato;
    }

    public Relasjon forkortetNavn(String forkortetNavn) {
        this.forkortetNavn = forkortetNavn;
        return this;
    }

    /**
     * Personidentifikator
     * @return forkortetNavn
     **/
    @JsonProperty("forkortetNavn")
    @ApiModelProperty(example = "01020304050", value = "Personidentifikator")
    public String getForkortetNavn() {
        return forkortetNavn;
    }

    public void setForkortetNavn(String forkortetNavn) {
        this.forkortetNavn = forkortetNavn;
    }

    public Relasjon harSammeAdresse(Boolean harSammeAdresse) {
        this.harSammeAdresse = harSammeAdresse;
        return this;
    }

    /**
     * Har samme adresse som Nav-Personidentifikator
     * @return harSammeAdresse
     **/
    @JsonProperty("harSammeAdresse")
    @ApiModelProperty(example = "true", value = "Har samme adresse som Nav-Personidentifikator")
    public Boolean isHarSammeAdresse() {
        return harSammeAdresse;
    }

    public void setHarSammeAdresse(Boolean harSammeAdresse) {
        this.harSammeAdresse = harSammeAdresse;
    }

    public Relasjon ident(String ident) {
        this.ident = ident;
        return this;
    }

    /**
     * Personidentifikator
     * @return ident
     **/
    @JsonProperty("ident")
    @ApiModelProperty(example = "01020304050", value = "Personidentifikator")
    public String getIdent() {
        return ident;
    }

    public void setIdent(String ident) {
        this.ident = ident;
    }

    public Relasjon kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public Relasjon kjoenn(String kjoenn) {
        this.kjoenn = kjoenn;
        return this;
    }

    /**
     * Kjønn
     * @return kjoenn
     **/
    @JsonProperty("kjoenn")
    @ApiModelProperty(example = "Mann", value = "Kjønn")
    public String getKjoenn() {
        return kjoenn;
    }

    public void setKjoenn(String kjoenn) {
        this.kjoenn = kjoenn;
    }

    public Relasjon relasjonsType(Kode relasjonsType) {
        this.relasjonsType = relasjonsType;
        return this;
    }

    /**
     * Get relasjonsType
     * @return relasjonsType
     **/
    @JsonProperty("relasjonsType")
    @ApiModelProperty(value = "")
    public Kode getRelasjonsType() {
        return relasjonsType;
    }

    public void setRelasjonsType(Kode relasjonsType) {
        this.relasjonsType = relasjonsType;
    }

    public Relasjon spesiellOpplysning(KodeMedDatoOgKilde spesiellOpplysning) {
        this.spesiellOpplysning = spesiellOpplysning;
        return this;
    }

    /**
     * Get spesiellOpplysning
     * @return spesiellOpplysning
     **/
    @JsonProperty("spesiellOpplysning")
    @ApiModelProperty(value = "")
    public KodeMedDatoOgKilde getSpesiellOpplysning() {
        return spesiellOpplysning;
    }

    public void setSpesiellOpplysning(KodeMedDatoOgKilde spesiellOpplysning) {
        this.spesiellOpplysning = spesiellOpplysning;
    }

    public Relasjon statsborgerskap(KodeMedDatoOgKilde statsborgerskap) {
        this.statsborgerskap = statsborgerskap;
        return this;
    }

    /**
     * Get statsborgerskap
     * @return statsborgerskap
     **/
    @JsonProperty("statsborgerskap")
    @ApiModelProperty(value = "")
    public KodeMedDatoOgKilde getStatsborgerskap() {
        return statsborgerskap;
    }

    public void setStatsborgerskap(KodeMedDatoOgKilde statsborgerskap) {
        this.statsborgerskap = statsborgerskap;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Relasjon relasjon = (Relasjon) o;
        return Objects.equals(this.alder, relasjon.alder) &&
                Objects.equals(this.datoFraOgMed, relasjon.datoFraOgMed) &&
                Objects.equals(this.doedsdato, relasjon.doedsdato) &&
                Objects.equals(this.egenansatt, relasjon.egenansatt) &&
                Objects.equals(this.foedselsdato, relasjon.foedselsdato) &&
                Objects.equals(this.forkortetNavn, relasjon.forkortetNavn) &&
                Objects.equals(this.harSammeAdresse, relasjon.harSammeAdresse) &&
                Objects.equals(this.ident, relasjon.ident) &&
                Objects.equals(this.kilde, relasjon.kilde) &&
                Objects.equals(this.kjoenn, relasjon.kjoenn) &&
                Objects.equals(this.relasjonsType, relasjon.relasjonsType) &&
                Objects.equals(this.spesiellOpplysning, relasjon.spesiellOpplysning) &&
                Objects.equals(this.statsborgerskap, relasjon.statsborgerskap);
    }

    @Override
    public int hashCode() {
        return Objects.hash(alder, datoFraOgMed, doedsdato, egenansatt, foedselsdato, forkortetNavn, harSammeAdresse, ident, kilde, kjoenn, relasjonsType, spesiellOpplysning, statsborgerskap);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Relasjon {\n");

        sb.append("    alder: ").append(toIndentedString(alder)).append("\n");
        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    doedsdato: ").append(toIndentedString(doedsdato)).append("\n");
        sb.append("    egenansatt: ").append(toIndentedString(egenansatt)).append("\n");
        sb.append("    foedselsdato: ").append(toIndentedString(foedselsdato)).append("\n");
        sb.append("    forkortetNavn: ").append(toIndentedString(forkortetNavn)).append("\n");
        sb.append("    harSammeAdresse: ").append(toIndentedString(harSammeAdresse)).append("\n");
        sb.append("    ident: ").append(toIndentedString(ident)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    kjoenn: ").append(toIndentedString(kjoenn)).append("\n");
        sb.append("    relasjonsType: ").append(toIndentedString(relasjonsType)).append("\n");
        sb.append("    spesiellOpplysning: ").append(toIndentedString(spesiellOpplysning)).append("\n");
        sb.append("    statsborgerskap: ").append(toIndentedString(statsborgerskap)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static final class Builder {
        private Integer alder;
        private String datoFraOgMed;
        private Doedsdato doedsdato;
        private Egenansatt egenansatt;
        private String foedselsdato;
        private String forkortetNavn;
        private Boolean harSammeAdresse;
        private String ident;
        private String kilde;
        private String kjoenn;
        private Kode relasjonsType;
        private KodeMedDatoOgKilde spesiellOpplysning;
        private KodeMedDatoOgKilde statsborgerskap;

        private Builder() {
        }

        public Builder withAlder(Integer alder) {
            this.alder = alder;
            return this;
        }

        public Builder withDatoFraOgMed(String datoFraOgMed) {
            this.datoFraOgMed = datoFraOgMed;
            return this;
        }

        public Builder withDoedsdato(Doedsdato doedsdato) {
            this.doedsdato = doedsdato;
            return this;
        }

        public Builder withEgenansatt(Egenansatt egenansatt) {
            this.egenansatt = egenansatt;
            return this;
        }

        public Builder withFoedselsdato(String foedselsdato) {
            this.foedselsdato = foedselsdato;
            return this;
        }

        public Builder withForkortetNavn(String forkortetNavn) {
            this.forkortetNavn = forkortetNavn;
            return this;
        }

        public Builder withHarSammeAdresse(Boolean harSammeAdresse) {
            this.harSammeAdresse = harSammeAdresse;
            return this;
        }

        public Builder withIdent(String ident) {
            this.ident = ident;
            return this;
        }

        public Builder withKilde(String kilde) {
            this.kilde = kilde;
            return this;
        }

        public Builder withKjoenn(String kjoenn) {
            this.kjoenn = kjoenn;
            return this;
        }

        public Builder withRelasjonsType(Kode relasjonsType) {
            this.relasjonsType = relasjonsType;
            return this;
        }

        public Builder withSpesiellOpplysning(KodeMedDatoOgKilde spesiellOpplysning) {
            this.spesiellOpplysning = spesiellOpplysning;
            return this;
        }

        public Builder withStatsborgerskap(KodeMedDatoOgKilde statsborgerskap) {
            this.statsborgerskap = statsborgerskap;
            return this;
        }

        public Relasjon build() {
            return new Relasjon(this);
        }
    }
}

