package no.nav.tps.proxy.api.v1.innsyn.dto;

/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Telefon kontaktinformasjon
 */
@ApiModel(description = "Telefon kontaktinformasjon")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Telefoninfo   {
    @JsonProperty("jobb")
    private String jobb = null;

    @JsonProperty("jobbDatoRegistrert")
    private String jobbDatoRegistrert = null;

    @JsonProperty("jobbKilde")
    private String jobbKilde = null;

    @JsonProperty("landkodeJobb")
    private String landkodeJobb = null;

    @JsonProperty("landkodeMobil")
    private String landkodeMobil = null;

    @JsonProperty("landkodePrivat")
    private String landkodePrivat = null;

    @JsonProperty("mobil")
    private String mobil = null;

    @JsonProperty("mobilDatoRegistrert")
    private String mobilDatoRegistrert = null;

    @JsonProperty("mobilKilde")
    private String mobilKilde = null;

    @JsonProperty("privat")
    private String privat = null;

    @JsonProperty("privatDatoRegistrert")
    private String privatDatoRegistrert = null;

    @JsonProperty("privatKilde")
    private String privatKilde = null;

    public Telefoninfo jobb(String jobb) {
        this.jobb = jobb;
        return this;
    }

    /**
     * Telefonnummer jobb
     * @return jobb
     **/
    @JsonProperty("jobb")
    @ApiModelProperty(example = "12345678", value = "Telefonnummer jobb")
    public String getJobb() {
        return jobb;
    }

    public void setJobb(String jobb) {
        this.jobb = jobb;
    }

    public Telefoninfo jobbDatoRegistrert(String jobbDatoRegistrert) {
        this.jobbDatoRegistrert = jobbDatoRegistrert;
        return this;
    }

    /**
     * Dato jobb telefonnummer registert, format (ISO-8601): yyyy-MM-dd
     * @return jobbDatoRegistrert
     **/
    @JsonProperty("jobbDatoRegistrert")
    @ApiModelProperty(example = "2015-12-15", value = "Dato jobb telefonnummer registert, format (ISO-8601): yyyy-MM-dd")
    public String getJobbDatoRegistrert() {
        return jobbDatoRegistrert;
    }

    public void setJobbDatoRegistrert(String jobbDatoRegistrert) {
        this.jobbDatoRegistrert = jobbDatoRegistrert;
    }

    public Telefoninfo jobbKilde(String jobbKilde) {
        this.jobbKilde = jobbKilde;
        return this;
    }

    /**
     * Get jobbKilde
     * @return jobbKilde
     **/
    @JsonProperty("jobbKilde")
    @ApiModelProperty(value = "")
    public String getJobbKilde() {
        return jobbKilde;
    }

    public void setJobbKilde(String jobbKilde) {
        this.jobbKilde = jobbKilde;
    }

    public Telefoninfo landkodeJobb(String landkodeJobb) {
        this.landkodeJobb = landkodeJobb;
        return this;
    }

    /**
     * Landkode jobb
     * @return landkodeJobb
     **/
    @JsonProperty("landkodeJobb")
    @ApiModelProperty(example = "+47", value = "Landkode jobb")
    public String getLandkodeJobb() {
        return landkodeJobb;
    }

    public void setLandkodeJobb(String landkodeJobb) {
        this.landkodeJobb = landkodeJobb;
    }

    public Telefoninfo landkodeMobil(String landkodeMobil) {
        this.landkodeMobil = landkodeMobil;
        return this;
    }

    /**
     * Landkode mobil
     * @return landkodeMobil
     **/
    @JsonProperty("landkodeMobil")
    @ApiModelProperty(example = "+47", value = "Landkode mobil")
    public String getLandkodeMobil() {
        return landkodeMobil;
    }

    public void setLandkodeMobil(String landkodeMobil) {
        this.landkodeMobil = landkodeMobil;
    }

    public Telefoninfo landkodePrivat(String landkodePrivat) {
        this.landkodePrivat = landkodePrivat;
        return this;
    }

    /**
     * Landkode privat
     * @return landkodePrivat
     **/
    @JsonProperty("landkodePrivat")
    @ApiModelProperty(example = "+47", value = "Landkode privat")
    public String getLandkodePrivat() {
        return landkodePrivat;
    }

    public void setLandkodePrivat(String landkodePrivat) {
        this.landkodePrivat = landkodePrivat;
    }

    public Telefoninfo mobil(String mobil) {
        this.mobil = mobil;
        return this;
    }

    /**
     * Telefonnummer mobil
     * @return mobil
     **/
    @JsonProperty("mobil")
    @ApiModelProperty(example = "12348765", value = "Telefonnummer mobil")
    public String getMobil() {
        return mobil;
    }

    public void setMobil(String mobil) {
        this.mobil = mobil;
    }

    public Telefoninfo mobilDatoRegistrert(String mobilDatoRegistrert) {
        this.mobilDatoRegistrert = mobilDatoRegistrert;
        return this;
    }

    /**
     * Dato mobil telefonnummer registert, format (ISO-8601): yyyy-MM-dd
     * @return mobilDatoRegistrert
     **/
    @JsonProperty("mobilDatoRegistrert")
    @ApiModelProperty(example = "2015-12-15", value = "Dato mobil telefonnummer registert, format (ISO-8601): yyyy-MM-dd")
    public String getMobilDatoRegistrert() {
        return mobilDatoRegistrert;
    }

    public void setMobilDatoRegistrert(String mobilDatoRegistrert) {
        this.mobilDatoRegistrert = mobilDatoRegistrert;
    }

    public Telefoninfo mobilKilde(String mobilKilde) {
        this.mobilKilde = mobilKilde;
        return this;
    }

    /**
     * Get mobilKilde
     * @return mobilKilde
     **/
    @JsonProperty("mobilKilde")
    @ApiModelProperty(value = "")
    public String getMobilKilde() {
        return mobilKilde;
    }

    public void setMobilKilde(String mobilKilde) {
        this.mobilKilde = mobilKilde;
    }

    public Telefoninfo privat(String privat) {
        this.privat = privat;
        return this;
    }

    /**
     * Telefonnummer privat
     * @return privat
     **/
    @JsonProperty("privat")
    @ApiModelProperty(example = "87654321", value = "Telefonnummer privat")
    public String getPrivat() {
        return privat;
    }

    public void setPrivat(String privat) {
        this.privat = privat;
    }

    public Telefoninfo privatDatoRegistrert(String privatDatoRegistrert) {
        this.privatDatoRegistrert = privatDatoRegistrert;
        return this;
    }

    /**
     * Dato privat telefonnummer registert, format (ISO-8601): yyyy-MM-dd
     * @return privatDatoRegistrert
     **/
    @JsonProperty("privatDatoRegistrert")
    @ApiModelProperty(example = "2015-12-15", value = "Dato privat telefonnummer registert, format (ISO-8601): yyyy-MM-dd")
    public String getPrivatDatoRegistrert() {
        return privatDatoRegistrert;
    }

    public void setPrivatDatoRegistrert(String privatDatoRegistrert) {
        this.privatDatoRegistrert = privatDatoRegistrert;
    }

    public Telefoninfo privatKilde(String privatKilde) {
        this.privatKilde = privatKilde;
        return this;
    }

    /**
     * Get privatKilde
     * @return privatKilde
     **/
    @JsonProperty("privatKilde")
    @ApiModelProperty(value = "")
    public String getPrivatKilde() {
        return privatKilde;
    }

    public void setPrivatKilde(String privatKilde) {
        this.privatKilde = privatKilde;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Telefoninfo telefoninfo = (Telefoninfo) o;
        return Objects.equals(this.jobb, telefoninfo.jobb) &&
                Objects.equals(this.jobbDatoRegistrert, telefoninfo.jobbDatoRegistrert) &&
                Objects.equals(this.jobbKilde, telefoninfo.jobbKilde) &&
                Objects.equals(this.landkodeJobb, telefoninfo.landkodeJobb) &&
                Objects.equals(this.landkodeMobil, telefoninfo.landkodeMobil) &&
                Objects.equals(this.landkodePrivat, telefoninfo.landkodePrivat) &&
                Objects.equals(this.mobil, telefoninfo.mobil) &&
                Objects.equals(this.mobilDatoRegistrert, telefoninfo.mobilDatoRegistrert) &&
                Objects.equals(this.mobilKilde, telefoninfo.mobilKilde) &&
                Objects.equals(this.privat, telefoninfo.privat) &&
                Objects.equals(this.privatDatoRegistrert, telefoninfo.privatDatoRegistrert) &&
                Objects.equals(this.privatKilde, telefoninfo.privatKilde);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jobb, jobbDatoRegistrert, jobbKilde, landkodeJobb, landkodeMobil, landkodePrivat, mobil, mobilDatoRegistrert, mobilKilde, privat, privatDatoRegistrert, privatKilde);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Telefoninfo {\n");

        sb.append("    jobb: ").append(toIndentedString(jobb)).append("\n");
        sb.append("    jobbDatoRegistrert: ").append(toIndentedString(jobbDatoRegistrert)).append("\n");
        sb.append("    jobbKilde: ").append(toIndentedString(jobbKilde)).append("\n");
        sb.append("    landkodeJobb: ").append(toIndentedString(landkodeJobb)).append("\n");
        sb.append("    landkodeMobil: ").append(toIndentedString(landkodeMobil)).append("\n");
        sb.append("    landkodePrivat: ").append(toIndentedString(landkodePrivat)).append("\n");
        sb.append("    mobil: ").append(toIndentedString(mobil)).append("\n");
        sb.append("    mobilDatoRegistrert: ").append(toIndentedString(mobilDatoRegistrert)).append("\n");
        sb.append("    mobilKilde: ").append(toIndentedString(mobilKilde)).append("\n");
        sb.append("    privat: ").append(toIndentedString(privat)).append("\n");
        sb.append("    privatDatoRegistrert: ").append(toIndentedString(privatDatoRegistrert)).append("\n");
        sb.append("    privatKilde: ").append(toIndentedString(privatKilde)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

