package no.nav.tps.proxy.api.v1.innsyn.dto;
/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon on tilleggsadresse
 */
@ApiModel(description = "Informasjon on tilleggsadresse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Tilleggsadresse   {
    @JsonProperty("adresse1")
    private String adresse1 = null;

    @JsonProperty("adresse2")
    private String adresse2 = null;

    @JsonProperty("adresse3")
    private String adresse3 = null;

    @JsonProperty("bolignummer")
    private String bolignummer = null;

    @JsonProperty("bydel")
    private String bydel = null;

    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("datoTilOgMed")
    private String datoTilOgMed = null;

    @JsonProperty("gateKode")
    private String gateKode = null;

    @JsonProperty("husbokstav")
    private String husbokstav = null;

    @JsonProperty("husnummer")
    private String husnummer = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("kommunenummer")
    private String kommunenummer = null;

    @JsonProperty("postboksanlegg")
    private String postboksanlegg = null;

    @JsonProperty("postboksnummer")
    private String postboksnummer = null;

    @JsonProperty("postnummer")
    private String postnummer = null;

    public Tilleggsadresse adresse1(String adresse1) {
        this.adresse1 = adresse1;
        return this;
    }

    /**
     * Adresselinje 1
     * @return adresse1
     **/
    @JsonProperty("adresse1")
    @ApiModelProperty(example = "V/TEST HUS", value = "Adresselinje 1")
    public String getAdresse1() {
        return adresse1;
    }

    public void setAdresse1(String adresse1) {
        this.adresse1 = adresse1;
    }

    public Tilleggsadresse adresse2(String adresse2) {
        this.adresse2 = adresse2;
        return this;
    }

    /**
     * Adresselinje 2
     * @return adresse2
     **/
    @JsonProperty("adresse2")
    @ApiModelProperty(example = "HUS 1 B", value = "Adresselinje 2")
    public String getAdresse2() {
        return adresse2;
    }

    public void setAdresse2(String adresse2) {
        this.adresse2 = adresse2;
    }

    public Tilleggsadresse adresse3(String adresse3) {
        this.adresse3 = adresse3;
        return this;
    }

    /**
     * Adresselinje 3
     * @return adresse3
     **/
    @JsonProperty("adresse3")
    @ApiModelProperty(value = "Adresselinje 3")
    public String getAdresse3() {
        return adresse3;
    }

    public void setAdresse3(String adresse3) {
        this.adresse3 = adresse3;
    }

    public Tilleggsadresse bolignummer(String bolignummer) {
        this.bolignummer = bolignummer;
        return this;
    }

    /**
     * Bolignummer
     * @return bolignummer
     **/
    @JsonProperty("bolignummer")
    @ApiModelProperty(example = "H0201", value = "Bolignummer")
    public String getBolignummer() {
        return bolignummer;
    }

    public void setBolignummer(String bolignummer) {
        this.bolignummer = bolignummer;
    }

    public Tilleggsadresse bydel(String bydel) {
        this.bydel = bydel;
        return this;
    }

    /**
     * Bydel
     * @return bydel
     **/
    @JsonProperty("bydel")
    @ApiModelProperty(example = "030929", value = "Bydel")
    public String getBydel() {
        return bydel;
    }

    public void setBydel(String bydel) {
        this.bydel = bydel;
    }

    public Tilleggsadresse datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public Tilleggsadresse datoTilOgMed(String datoTilOgMed) {
        this.datoTilOgMed = datoTilOgMed;
        return this;
    }

    /**
     * Dato til når informasjonen er gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoTilOgMed
     **/
    @JsonProperty("datoTilOgMed")
    @ApiModelProperty(example = "2016-09-11", value = "Dato til når informasjonen er gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoTilOgMed() {
        return datoTilOgMed;
    }

    public void setDatoTilOgMed(String datoTilOgMed) {
        this.datoTilOgMed = datoTilOgMed;
    }

    public Tilleggsadresse gateKode(String gateKode) {
        this.gateKode = gateKode;
        return this;
    }

    /**
     * Gatekoade
     * @return gateKode
     **/
    @JsonProperty("gateKode")
    @ApiModelProperty(example = "01151", value = "Gatekoade")
    public String getGateKode() {
        return gateKode;
    }

    public void setGateKode(String gateKode) {
        this.gateKode = gateKode;
    }

    public Tilleggsadresse husbokstav(String husbokstav) {
        this.husbokstav = husbokstav;
        return this;
    }

    /**
     * Husbokstav
     * @return husbokstav
     **/
    @JsonProperty("husbokstav")
    @ApiModelProperty(example = "B", value = "Husbokstav")
    public String getHusbokstav() {
        return husbokstav;
    }

    public void setHusbokstav(String husbokstav) {
        this.husbokstav = husbokstav;
    }

    public Tilleggsadresse husnummer(String husnummer) {
        this.husnummer = husnummer;
        return this;
    }

    /**
     * Husnummer
     * @return husnummer
     **/
    @JsonProperty("husnummer")
    @ApiModelProperty(example = "0989", value = "Husnummer")
    public String getHusnummer() {
        return husnummer;
    }

    public void setHusnummer(String husnummer) {
        this.husnummer = husnummer;
    }

    public Tilleggsadresse kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public Tilleggsadresse kommunenummer(String kommunenummer) {
        this.kommunenummer = kommunenummer;
        return this;
    }

    /**
     * Kommunenummer
     * @return kommunenummer
     **/
    @JsonProperty("kommunenummer")
    @ApiModelProperty(example = "1333", value = "Kommunenummer")
    public String getKommunenummer() {
        return kommunenummer;
    }

    public void setKommunenummer(String kommunenummer) {
        this.kommunenummer = kommunenummer;
    }

    public Tilleggsadresse postboksanlegg(String postboksanlegg) {
        this.postboksanlegg = postboksanlegg;
        return this;
    }

    /**
     * Get postboksanlegg
     * @return postboksanlegg
     **/
    @JsonProperty("postboksanlegg")
    @ApiModelProperty(value = "")
    public String getPostboksanlegg() {
        return postboksanlegg;
    }

    public void setPostboksanlegg(String postboksanlegg) {
        this.postboksanlegg = postboksanlegg;
    }

    public Tilleggsadresse postboksnummer(String postboksnummer) {
        this.postboksnummer = postboksnummer;
        return this;
    }

    /**
     * Get postboksnummer
     * @return postboksnummer
     **/
    @JsonProperty("postboksnummer")
    @ApiModelProperty(value = "")
    public String getPostboksnummer() {
        return postboksnummer;
    }

    public void setPostboksnummer(String postboksnummer) {
        this.postboksnummer = postboksnummer;
    }

    public Tilleggsadresse postnummer(String postnummer) {
        this.postnummer = postnummer;
        return this;
    }

    /**
     * Postnummer
     * @return postnummer
     **/
    @JsonProperty("postnummer")
    @ApiModelProperty(example = "5200", value = "Postnummer")
    public String getPostnummer() {
        return postnummer;
    }

    public void setPostnummer(String postnummer) {
        this.postnummer = postnummer;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Tilleggsadresse tilleggsadresse = (Tilleggsadresse) o;
        return Objects.equals(this.adresse1, tilleggsadresse.adresse1) &&
                Objects.equals(this.adresse2, tilleggsadresse.adresse2) &&
                Objects.equals(this.adresse3, tilleggsadresse.adresse3) &&
                Objects.equals(this.bolignummer, tilleggsadresse.bolignummer) &&
                Objects.equals(this.bydel, tilleggsadresse.bydel) &&
                Objects.equals(this.datoFraOgMed, tilleggsadresse.datoFraOgMed) &&
                Objects.equals(this.datoTilOgMed, tilleggsadresse.datoTilOgMed) &&
                Objects.equals(this.gateKode, tilleggsadresse.gateKode) &&
                Objects.equals(this.husbokstav, tilleggsadresse.husbokstav) &&
                Objects.equals(this.husnummer, tilleggsadresse.husnummer) &&
                Objects.equals(this.kilde, tilleggsadresse.kilde) &&
                Objects.equals(this.kommunenummer, tilleggsadresse.kommunenummer) &&
                Objects.equals(this.postboksanlegg, tilleggsadresse.postboksanlegg) &&
                Objects.equals(this.postboksnummer, tilleggsadresse.postboksnummer) &&
                Objects.equals(this.postnummer, tilleggsadresse.postnummer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(adresse1, adresse2, adresse3, bolignummer, bydel, datoFraOgMed, datoTilOgMed, gateKode, husbokstav, husnummer, kilde, kommunenummer, postboksanlegg, postboksnummer, postnummer);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Tilleggsadresse {\n");

        sb.append("    adresse1: ").append(toIndentedString(adresse1)).append("\n");
        sb.append("    adresse2: ").append(toIndentedString(adresse2)).append("\n");
        sb.append("    adresse3: ").append(toIndentedString(adresse3)).append("\n");
        sb.append("    bolignummer: ").append(toIndentedString(bolignummer)).append("\n");
        sb.append("    bydel: ").append(toIndentedString(bydel)).append("\n");
        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    datoTilOgMed: ").append(toIndentedString(datoTilOgMed)).append("\n");
        sb.append("    gateKode: ").append(toIndentedString(gateKode)).append("\n");
        sb.append("    husbokstav: ").append(toIndentedString(husbokstav)).append("\n");
        sb.append("    husnummer: ").append(toIndentedString(husnummer)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    kommunenummer: ").append(toIndentedString(kommunenummer)).append("\n");
        sb.append("    postboksanlegg: ").append(toIndentedString(postboksanlegg)).append("\n");
        sb.append("    postboksnummer: ").append(toIndentedString(postboksnummer)).append("\n");
        sb.append("    postnummer: ").append(toIndentedString(postnummer)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

