package no.nav.tps.proxy.api.v1.innsyn.dto;

/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon on tiltak
 */
@ApiModel(description = "Informasjon on tiltak")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Tiltak   {
    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("datoTil")
    private String datoTil = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("type")
    private Kode type = null;

    public Tiltak datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public Tiltak datoTil(String datoTil) {
        this.datoTil = datoTil;
        return this;
    }

    /**
     * Dato til når informasjonen er gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoTil
     **/
    @JsonProperty("datoTil")
    @ApiModelProperty(example = "2016-09-11", value = "Dato til når informasjonen er gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoTil() {
        return datoTil;
    }

    public void setDatoTil(String datoTil) {
        this.datoTil = datoTil;
    }

    public Tiltak kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public Tiltak type(Kode type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     **/
    @JsonProperty("type")
    @ApiModelProperty(value = "")
    public Kode getType() {
        return type;
    }

    public void setType(Kode type) {
        this.type = type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Tiltak tiltak = (Tiltak) o;
        return Objects.equals(this.datoFraOgMed, tiltak.datoFraOgMed) &&
                Objects.equals(this.datoTil, tiltak.datoTil) &&
                Objects.equals(this.kilde, tiltak.kilde) &&
                Objects.equals(this.type, tiltak.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datoFraOgMed, datoTil, kilde, type);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Tiltak {\n");

        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    datoTil: ").append(toIndentedString(datoTil)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

