package no.nav.tps.proxy.api.v1.innsyn.dto;
/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om utenlandsk bank
 */
@ApiModel(description = "Informasjon om utenlandsk bank")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class UtenlandskBank   {
    @JsonProperty("adresse1")
    private String adresse1 = null;

    @JsonProperty("adresse2")
    private String adresse2 = null;

    @JsonProperty("adresse3")
    private String adresse3 = null;

    @JsonProperty("bankkode")
    private String bankkode = null;

    @JsonProperty("banknavn")
    private String banknavn = null;

    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("iban")
    private String iban = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("kontonummer")
    private String kontonummer = null;

    @JsonProperty("land")
    private Kode land = null;

    @JsonProperty("swiftkode")
    private String swiftkode = null;

    @JsonProperty("valuta")
    private Kode valuta = null;

    public UtenlandskBank adresse1(String adresse1) {
        this.adresse1 = adresse1;
        return this;
    }

    /**
     * Bank adresselinje 1
     * @return adresse1
     **/
    @JsonProperty("adresse1")
    @ApiModelProperty(example = "Test Road 89", value = "Bank adresselinje 1")
    public String getAdresse1() {
        return adresse1;
    }

    public void setAdresse1(String adresse1) {
        this.adresse1 = adresse1;
    }

    public UtenlandskBank adresse2(String adresse2) {
        this.adresse2 = adresse2;
        return this;
    }

    /**
     * Bank adresselinje 2
     * @return adresse2
     **/
    @JsonProperty("adresse2")
    @ApiModelProperty(example = "56819 Test T", value = "Bank adresselinje 2")
    public String getAdresse2() {
        return adresse2;
    }

    public void setAdresse2(String adresse2) {
        this.adresse2 = adresse2;
    }

    public UtenlandskBank adresse3(String adresse3) {
        this.adresse3 = adresse3;
        return this;
    }

    /**
     * Bank adreeselinje 3
     * @return adresse3
     **/
    @JsonProperty("adresse3")
    @ApiModelProperty(example = "NORGE", value = "Bank adreeselinje 3")
    public String getAdresse3() {
        return adresse3;
    }

    public void setAdresse3(String adresse3) {
        this.adresse3 = adresse3;
    }

    public UtenlandskBank bankkode(String bankkode) {
        this.bankkode = bankkode;
        return this;
    }

    /**
     * Bankkode
     * @return bankkode
     **/
    @JsonProperty("bankkode")
    @ApiModelProperty(example = "37040044", value = "Bankkode")
    public String getBankkode() {
        return bankkode;
    }

    public void setBankkode(String bankkode) {
        this.bankkode = bankkode;
    }

    public UtenlandskBank banknavn(String banknavn) {
        this.banknavn = banknavn;
        return this;
    }

    /**
     * Banknavn
     * @return banknavn
     **/
    @JsonProperty("banknavn")
    @ApiModelProperty(example = "Testching", value = "Banknavn")
    public String getBanknavn() {
        return banknavn;
    }

    public void setBanknavn(String banknavn) {
        this.banknavn = banknavn;
    }

    public UtenlandskBank datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public UtenlandskBank iban(String iban) {
        this.iban = iban;
        return this;
    }

    /**
     * IBAN
     * @return iban
     **/
    @JsonProperty("iban")
    @ApiModelProperty(example = "DE89 3704 0044 0532 0130 00", value = "IBAN")
    public String getIban() {
        return iban;
    }

    public void setIban(String iban) {
        this.iban = iban;
    }

    public UtenlandskBank kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public UtenlandskBank kontonummer(String kontonummer) {
        this.kontonummer = kontonummer;
        return this;
    }

    /**
     * Kontonummer
     * @return kontonummer
     **/
    @JsonProperty("kontonummer")
    @ApiModelProperty(example = "SE73CLEI4532196738224", value = "Kontonummer")
    public String getKontonummer() {
        return kontonummer;
    }

    public void setKontonummer(String kontonummer) {
        this.kontonummer = kontonummer;
    }

    public UtenlandskBank land(Kode land) {
        this.land = land;
        return this;
    }

    /**
     * Get land
     * @return land
     **/
    @JsonProperty("land")
    @ApiModelProperty(value = "")
    public Kode getLand() {
        return land;
    }

    public void setLand(Kode land) {
        this.land = land;
    }

    public UtenlandskBank swiftkode(String swiftkode) {
        this.swiftkode = swiftkode;
        return this;
    }

    /**
     * Swift kode
     * @return swiftkode
     **/
    @JsonProperty("swiftkode")
    @ApiModelProperty(example = "QYTESTCÅ", value = "Swift kode")
    public String getSwiftkode() {
        return swiftkode;
    }

    public void setSwiftkode(String swiftkode) {
        this.swiftkode = swiftkode;
    }

    public UtenlandskBank valuta(Kode valuta) {
        this.valuta = valuta;
        return this;
    }

    /**
     * Get valuta
     * @return valuta
     **/
    @JsonProperty("valuta")
    @ApiModelProperty(value = "")
    public Kode getValuta() {
        return valuta;
    }

    public void setValuta(Kode valuta) {
        this.valuta = valuta;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UtenlandskBank utenlandskBank = (UtenlandskBank) o;
        return Objects.equals(this.adresse1, utenlandskBank.adresse1) &&
                Objects.equals(this.adresse2, utenlandskBank.adresse2) &&
                Objects.equals(this.adresse3, utenlandskBank.adresse3) &&
                Objects.equals(this.bankkode, utenlandskBank.bankkode) &&
                Objects.equals(this.banknavn, utenlandskBank.banknavn) &&
                Objects.equals(this.datoFraOgMed, utenlandskBank.datoFraOgMed) &&
                Objects.equals(this.iban, utenlandskBank.iban) &&
                Objects.equals(this.kilde, utenlandskBank.kilde) &&
                Objects.equals(this.kontonummer, utenlandskBank.kontonummer) &&
                Objects.equals(this.land, utenlandskBank.land) &&
                Objects.equals(this.swiftkode, utenlandskBank.swiftkode) &&
                Objects.equals(this.valuta, utenlandskBank.valuta);
    }

    @Override
    public int hashCode() {
        return Objects.hash(adresse1, adresse2, adresse3, bankkode, banknavn, datoFraOgMed, iban, kilde, kontonummer, land, swiftkode, valuta);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UtenlandskBank {\n");

        sb.append("    adresse1: ").append(toIndentedString(adresse1)).append("\n");
        sb.append("    adresse2: ").append(toIndentedString(adresse2)).append("\n");
        sb.append("    adresse3: ").append(toIndentedString(adresse3)).append("\n");
        sb.append("    bankkode: ").append(toIndentedString(bankkode)).append("\n");
        sb.append("    banknavn: ").append(toIndentedString(banknavn)).append("\n");
        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    kontonummer: ").append(toIndentedString(kontonummer)).append("\n");
        sb.append("    land: ").append(toIndentedString(land)).append("\n");
        sb.append("    swiftkode: ").append(toIndentedString(swiftkode)).append("\n");
        sb.append("    valuta: ").append(toIndentedString(valuta)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

