package no.nav.tps.proxy.api.v1.innsyn.dto;
/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om utenlandsk adresse
 */
@ApiModel(description = "Informasjon om utenlandsk adresse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class UtenlandskAdresse   {
    @JsonProperty("adresse1")
    private String adresse1 = null;

    @JsonProperty("adresse2")
    private String adresse2 = null;

    @JsonProperty("adresse3")
    private String adresse3 = null;

    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("datoTilOgMed")
    private String datoTilOgMed = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("land")
    private String land = null;

    public UtenlandskAdresse adresse1(String adresse1) {
        this.adresse1 = adresse1;
        return this;
    }

    /**
     * Adresselinje 1
     * @return adresse1
     **/
    @JsonProperty("adresse1")
    @ApiModelProperty(example = "TESTLAN 13", value = "Adresselinje 1")
    public String getAdresse1() {
        return adresse1;
    }

    public void setAdresse1(String adresse1) {
        this.adresse1 = adresse1;
    }

    public UtenlandskAdresse adresse2(String adresse2) {
        this.adresse2 = adresse2;
        return this;
    }

    /**
     * Adresselinje 2
     * @return adresse2
     **/
    @JsonProperty("adresse2")
    @ApiModelProperty(example = "TEST", value = "Adresselinje 2")
    public String getAdresse2() {
        return adresse2;
    }

    public void setAdresse2(String adresse2) {
        this.adresse2 = adresse2;
    }

    public UtenlandskAdresse adresse3(String adresse3) {
        this.adresse3 = adresse3;
        return this;
    }

    /**
     * Adresselinje 3
     * @return adresse3
     **/
    @JsonProperty("adresse3")
    @ApiModelProperty(example = "IRAK", value = "Adresselinje 3")
    public String getAdresse3() {
        return adresse3;
    }

    public void setAdresse3(String adresse3) {
        this.adresse3 = adresse3;
    }

    public UtenlandskAdresse datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public UtenlandskAdresse datoTilOgMed(String datoTilOgMed) {
        this.datoTilOgMed = datoTilOgMed;
        return this;
    }

    /**
     * Dato til når informasjonen er gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoTilOgMed
     **/
    @JsonProperty("datoTilOgMed")
    @ApiModelProperty(example = "2011-11-11", value = "Dato til når informasjonen er gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoTilOgMed() {
        return datoTilOgMed;
    }

    public void setDatoTilOgMed(String datoTilOgMed) {
        this.datoTilOgMed = datoTilOgMed;
    }

    public UtenlandskAdresse kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public UtenlandskAdresse land(String land) {
        this.land = land;
        return this;
    }

    /**
     * Landkode
     * @return land
     **/
    @JsonProperty("land")
    @ApiModelProperty(example = "IRQ", value = "Landkode")
    public String getLand() {
        return land;
    }

    public void setLand(String land) {
        this.land = land;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UtenlandskAdresse utenlandskAdresse = (UtenlandskAdresse) o;
        return Objects.equals(this.adresse1, utenlandskAdresse.adresse1) &&
                Objects.equals(this.adresse2, utenlandskAdresse.adresse2) &&
                Objects.equals(this.adresse3, utenlandskAdresse.adresse3) &&
                Objects.equals(this.datoFraOgMed, utenlandskAdresse.datoFraOgMed) &&
                Objects.equals(this.datoTilOgMed, utenlandskAdresse.datoTilOgMed) &&
                Objects.equals(this.kilde, utenlandskAdresse.kilde) &&
                Objects.equals(this.land, utenlandskAdresse.land);
    }

    @Override
    public int hashCode() {
        return Objects.hash(adresse1, adresse2, adresse3, datoFraOgMed, datoTilOgMed, kilde, land);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UtenlandskAdresse {\n");

        sb.append("    adresse1: ").append(toIndentedString(adresse1)).append("\n");
        sb.append("    adresse2: ").append(toIndentedString(adresse2)).append("\n");
        sb.append("    adresse3: ").append(toIndentedString(adresse3)).append("\n");
        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    datoTilOgMed: ").append(toIndentedString(datoTilOgMed)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    land: ").append(toIndentedString(land)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

