package no.nav.tps.proxy.api.v1.innsyn.dto;
/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om veiadresse
 */
@ApiModel(description = "Informasjon om veiadresse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Veiadresse   {
    @JsonProperty("bokstav")
    private String bokstav = null;

    @JsonProperty("bolignummer")
    private String bolignummer = null;

    @JsonProperty("gatekode")
    private String gatekode = null;

    @JsonProperty("husnummer")
    private String husnummer = null;

    public Veiadresse bokstav(String bokstav) {
        this.bokstav = bokstav;
        return this;
    }

    /**
     * Husbokstav
     * @return bokstav
     **/
    @JsonProperty("bokstav")
    @ApiModelProperty(example = "C", value = "Husbokstav")
    public String getBokstav() {
        return bokstav;
    }

    public void setBokstav(String bokstav) {
        this.bokstav = bokstav;
    }

    public Veiadresse bolignummer(String bolignummer) {
        this.bolignummer = bolignummer;
        return this;
    }

    /**
     * Bolignummer
     * @return bolignummer
     **/
    @JsonProperty("bolignummer")
    @ApiModelProperty(example = "H0402", value = "Bolignummer")
    public String getBolignummer() {
        return bolignummer;
    }

    public void setBolignummer(String bolignummer) {
        this.bolignummer = bolignummer;
    }

    public Veiadresse gatekode(String gatekode) {
        this.gatekode = gatekode;
        return this;
    }

    /**
     * Gatekode
     * @return gatekode
     **/
    @JsonProperty("gatekode")
    @ApiModelProperty(example = "01038", value = "Gatekode")
    public String getGatekode() {
        return gatekode;
    }

    public void setGatekode(String gatekode) {
        this.gatekode = gatekode;
    }

    public Veiadresse husnummer(String husnummer) {
        this.husnummer = husnummer;
        return this;
    }

    /**
     * Husnummer
     * @return husnummer
     **/
    @JsonProperty("husnummer")
    @ApiModelProperty(example = "0085", value = "Husnummer")
    public String getHusnummer() {
        return husnummer;
    }

    public void setHusnummer(String husnummer) {
        this.husnummer = husnummer;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Veiadresse veiadresse = (Veiadresse) o;
        return Objects.equals(this.bokstav, veiadresse.bokstav) &&
                Objects.equals(this.bolignummer, veiadresse.bolignummer) &&
                Objects.equals(this.gatekode, veiadresse.gatekode) &&
                Objects.equals(this.husnummer, veiadresse.husnummer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bokstav, bolignummer, gatekode, husnummer);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Veiadresse {\n");

        sb.append("    bokstav: ").append(toIndentedString(bokstav)).append("\n");
        sb.append("    bolignummer: ").append(toIndentedString(bolignummer)).append("\n");
        sb.append("    gatekode: ").append(toIndentedString(gatekode)).append("\n");
        sb.append("    husnummer: ").append(toIndentedString(husnummer)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

