package no.nav.tps.proxy.api.v1.innsyn.dto;
/*
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Informasjon om vergemål
 */
@ApiModel(description = "Informasjon om vergemål")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-11-27T10:31:32.432+01:00")
public class Vergemaal   {
    @JsonProperty("datoFraOgMed")
    private String datoFraOgMed = null;

    @JsonProperty("egenansatt")
    private Boolean egenansatt = null;

    @JsonProperty("embete")
    private Kode embete = null;

    @JsonProperty("fnr")
    private String fnr = null;

    @JsonProperty("forkortetNavn")
    private String forkortetNavn = null;

    @JsonProperty("id")
    private String id = null;

    @JsonProperty("kilde")
    private String kilde = null;

    @JsonProperty("mandattype")
    private Kode mandattype = null;

    @JsonProperty("saksId")
    private String saksId = null;

    @JsonProperty("sakstype")
    private Kode sakstype = null;

    @JsonProperty("spesreg")
    private Kode spesreg = null;

    @JsonProperty("type")
    private Kode type = null;

    @JsonProperty("vedtaksdato")
    private String vedtaksdato = null;

    public Vergemaal datoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
        return this;
    }

    /**
     * Dato gyldig, format (ISO-8601): yyyy-MM-dd
     * @return datoFraOgMed
     **/
    @JsonProperty("datoFraOgMed")
    @ApiModelProperty(example = "2015-12-15", value = "Dato gyldig, format (ISO-8601): yyyy-MM-dd")
    public String getDatoFraOgMed() {
        return datoFraOgMed;
    }

    public void setDatoFraOgMed(String datoFraOgMed) {
        this.datoFraOgMed = datoFraOgMed;
    }

    public Vergemaal egenansatt(Boolean egenansatt) {
        this.egenansatt = egenansatt;
        return this;
    }

    /**
     * Verge egenansatt
     * @return egenansatt
     **/
    @JsonProperty("egenansatt")
    @ApiModelProperty(example = "false", value = "Verge egenansatt")
    public Boolean isEgenansatt() {
        return egenansatt;
    }

    public void setEgenansatt(Boolean egenansatt) {
        this.egenansatt = egenansatt;
    }

    public Vergemaal embete(Kode embete) {
        this.embete = embete;
        return this;
    }

    /**
     * Get embete
     * @return embete
     **/
    @JsonProperty("embete")
    @ApiModelProperty(value = "")
    public Kode getEmbete() {
        return embete;
    }

    public void setEmbete(Kode embete) {
        this.embete = embete;
    }

    public Vergemaal fnr(String fnr) {
        this.fnr = fnr;
        return this;
    }

    /**
     * Fødselsnummer
     * @return fnr
     **/
    @JsonProperty("fnr")
    @ApiModelProperty(example = "12095847763", value = "Fødselsnummer")
    public String getFnr() {
        return fnr;
    }

    public void setFnr(String fnr) {
        this.fnr = fnr;
    }

    public Vergemaal forkortetNavn(String forkortetNavn) {
        this.forkortetNavn = forkortetNavn;
        return this;
    }

    /**
     * Verge forkortet navn
     * @return forkortetNavn
     **/
    @JsonProperty("forkortetNavn")
    @ApiModelProperty(example = "TJUSBERG OUBAH-MASK", value = "Verge forkortet navn")
    public String getForkortetNavn() {
        return forkortetNavn;
    }

    public void setForkortetNavn(String forkortetNavn) {
        this.forkortetNavn = forkortetNavn;
    }

    public Vergemaal id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Id
     * @return id
     **/
    @JsonProperty("id")
    @ApiModelProperty(example = "000129159", value = "Id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Vergemaal kilde(String kilde) {
        this.kilde = kilde;
        return this;
    }

    /**
     * Get kilde
     * @return kilde
     **/
    @JsonProperty("kilde")
    @ApiModelProperty(value = "")
    public String getKilde() {
        return kilde;
    }

    public void setKilde(String kilde) {
        this.kilde = kilde;
    }

    public Vergemaal mandattype(Kode mandattype) {
        this.mandattype = mandattype;
        return this;
    }

    /**
     * Get mandattype
     * @return mandattype
     **/
    @JsonProperty("mandattype")
    @ApiModelProperty(value = "")
    public Kode getMandattype() {
        return mandattype;
    }

    public void setMandattype(Kode mandattype) {
        this.mandattype = mandattype;
    }

    public Vergemaal saksId(String saksId) {
        this.saksId = saksId;
        return this;
    }

    /**
     * Saksid
     * @return saksId
     **/
    @JsonProperty("saksId")
    @ApiModelProperty(example = "000129154", value = "Saksid")
    public String getSaksId() {
        return saksId;
    }

    public void setSaksId(String saksId) {
        this.saksId = saksId;
    }

    public Vergemaal sakstype(Kode sakstype) {
        this.sakstype = sakstype;
        return this;
    }

    /**
     * Get sakstype
     * @return sakstype
     **/
    @JsonProperty("sakstype")
    @ApiModelProperty(value = "")
    public Kode getSakstype() {
        return sakstype;
    }

    public void setSakstype(Kode sakstype) {
        this.sakstype = sakstype;
    }

    public Vergemaal spesreg(Kode spesreg) {
        this.spesreg = spesreg;
        return this;
    }

    /**
     * Get spesreg
     * @return spesreg
     **/
    @JsonProperty("spesreg")
    @ApiModelProperty(value = "")
    public Kode getSpesreg() {
        return spesreg;
    }

    public void setSpesreg(Kode spesreg) {
        this.spesreg = spesreg;
    }

    public Vergemaal type(Kode type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     **/
    @JsonProperty("type")
    @ApiModelProperty(value = "")
    public Kode getType() {
        return type;
    }

    public void setType(Kode type) {
        this.type = type;
    }

    public Vergemaal vedtaksdato(String vedtaksdato) {
        this.vedtaksdato = vedtaksdato;
        return this;
    }

    /**
     * Dato for vedtak, format (ISO-8601): yyyy-MM-dd
     * @return vedtaksdato
     **/
    @JsonProperty("vedtaksdato")
    @ApiModelProperty(example = "1981-12-12", value = "Dato for vedtak, format (ISO-8601): yyyy-MM-dd")
    public String getVedtaksdato() {
        return vedtaksdato;
    }

    public void setVedtaksdato(String vedtaksdato) {
        this.vedtaksdato = vedtaksdato;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Vergemaal vergemaal = (Vergemaal) o;
        return Objects.equals(this.datoFraOgMed, vergemaal.datoFraOgMed) &&
                Objects.equals(this.egenansatt, vergemaal.egenansatt) &&
                Objects.equals(this.embete, vergemaal.embete) &&
                Objects.equals(this.fnr, vergemaal.fnr) &&
                Objects.equals(this.forkortetNavn, vergemaal.forkortetNavn) &&
                Objects.equals(this.id, vergemaal.id) &&
                Objects.equals(this.kilde, vergemaal.kilde) &&
                Objects.equals(this.mandattype, vergemaal.mandattype) &&
                Objects.equals(this.saksId, vergemaal.saksId) &&
                Objects.equals(this.sakstype, vergemaal.sakstype) &&
                Objects.equals(this.spesreg, vergemaal.spesreg) &&
                Objects.equals(this.type, vergemaal.type) &&
                Objects.equals(this.vedtaksdato, vergemaal.vedtaksdato);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datoFraOgMed, egenansatt, embete, fnr, forkortetNavn, id, kilde, mandattype, saksId, sakstype, spesreg, type, vedtaksdato);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Vergemaal {\n");

        sb.append("    datoFraOgMed: ").append(toIndentedString(datoFraOgMed)).append("\n");
        sb.append("    egenansatt: ").append(toIndentedString(egenansatt)).append("\n");
        sb.append("    embete: ").append(toIndentedString(embete)).append("\n");
        sb.append("    fnr: ").append(toIndentedString(fnr)).append("\n");
        sb.append("    forkortetNavn: ").append(toIndentedString(forkortetNavn)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    kilde: ").append(toIndentedString(kilde)).append("\n");
        sb.append("    mandattype: ").append(toIndentedString(mandattype)).append("\n");
        sb.append("    saksId: ").append(toIndentedString(saksId)).append("\n");
        sb.append("    sakstype: ").append(toIndentedString(sakstype)).append("\n");
        sb.append("    spesreg: ").append(toIndentedString(spesreg)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    vedtaksdato: ").append(toIndentedString(vedtaksdato)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

