package no.nav.foreldrepenger.fpmock2.testmodell.inntektytelse.inntektkomponent;

public class InntektBeskrivelse {

    //TODO: Ola implementer
}


/*
Ref: https://app-t11.adeo.no/inntektstub/api/v1/kodeverk/Loennsbeskrivelse
[
{"navn":"aksjerGrunnfondsbevisTilUnderkurs","term":"Aksjer/grunnfondsbevis til underkurs"},
{"navn":"annet","term":"Annet"},
{"navn":"arbeidsoppholdKost","term":"Arbeidsopphold kost"},
{"navn":"arbeidsoppholdLosji","term":"Arbeidsopphold losji"},
{"navn":"bedriftsbarnehageplass","term":"Bedriftsbarnehageplass"},
{"navn":"beregnetSkatt","term":"Beregnet skatt"},
{"navn":"besoeksreiserHjemmetAnnet","term":"Besøksreiser hjemmet annet"},
{"navn":"besoeksreiserHjemmetKilometergodtgjoerelseBil","term":"Besøksreiser hjemmet kilometergodtgjørelse bil"},
{"navn":"besoeksreiserHjemmetKost","term":"Besøksreiser hjemmet kost"},
{"navn":"betaltUtenlandskSkatt","term":"Betalt utenlandsk skatt"},
{"navn":"bil","term":"Bil"},
{"navn":"bolig","term":"Bolig"},
{"navn":"bonus","term":"Bonus"},
{"navn":"bonusFraForsvaret","term":"Bonus fra forsvaret"},
{"navn":"elektroniskKommunikasjon","term":"Elektronisk kommunikasjon"},
{"navn":"fastBilgodtgjoerelse","term":"Fast bilgodtgjørelse"},
{"navn":"fastTillegg","term":"Faste tillegg"},
{"navn":"fastloenn","term":"Fastlønn"},
{"navn":"feriepenger","term":"Feriepenger"},
{"navn":"flyttegodtgjoerelse","term":"Flyttegodtgjørelse mv"},
{"navn":"fondForIdrettsutoevere","term":"Fond for idrettsutøvere"},
{"navn":"friTransport","term":"Fri transport"},
{"navn":"godtgjoerelseSaeravtaleUtland","term":"Godtgjørelse i henhold til særavtale utland"},
{"navn":"helligdagstillegg","term":"Helligdagstillegg"},
{"navn":"honorarAkkordProsentProvisjon","term":"Honorar/Akkord/Prosent/Provisjon"},
{"navn":"hyretillegg","term":"Hyretillegg"},
{"navn":"ikkeSkattepliktigLoennFraUtenlandskDiplomKonsulStasjon","term":"Lønn mv som ikke er skattepliktig i Norge fra utenlandsk diplomatisk eller konsulær stasjon"},
{"navn":"innbetalingTilUtenlandskPensjonsordning","term":"Innbetaling til utenlandsk pensjonsordning"},
{"navn":"kapitalInntekt","term":"Kapitalinntekt"},
{"navn":"kilometergodtgjoerelseAndreFremkomstmidler","term":"Kilometergodtgjørelse andre fremkomstmidler"},
{"navn":"kilometergodtgjoerelseBil","term":"Kilometergodtgjørelse bil"},
{"navn":"kilometergodtgjoerelseElBil","term":"Kilometergodtgjørelse el-bil"},
{"navn":"kilometergodtgjoerelsePassasjertillegg","term":"Kilometergodtgjørelse passasjertillegg"},
{"navn":"kommunalOmsorgsloennOgFosterhjemsgodtgjoerelse","term":"Kommunal omsorgslønn og fosterhjemsgodtgjørelse"},
{"navn":"kompensasjonstilleggBolig","term":"Kompensasjonstillegg bolig"},
{"navn":"kostDager","term":"Kost (dager)"},
{"navn":"kostDoegn","term":"Kost (døgn)"},
{"navn":"kostbesparelseIHjemmet","term":"Kostbesparelse i hjemmet"},
{"navn":"loennEtterDoedsfall","term":"Lønn etter dødsfall"},
{"navn":"loennForBarnepassIBarnetsHjem","term":"Lønn og godtgjørelse til dagmamma eller praktikant som passer barn i barnets hjem"},
{"navn":"loennTilPrivatpersonerForArbeidIHjemmet","term":"Lønn og godtgjørelse til privatpersoner for arbeidsoppdrag i oppdragsgivers hjem"},
{"navn":"loennTilVergeFraFylkesmannen","term":"Lønn til verge fra Fylkesmannen"},
{"navn":"loennUtbetaltAvVeldedigEllerAllmennyttigInstitusjonEllerOrganisasjon","term":"Lønn og godtgjørelse utbetalt av veldedig eller allmennyttig institusjon eller organisasjon"},
{"navn":"loennUtenlandskArtist","term":"Lønn utenlandsk artist"},
{"navn":"losji","term":"Losji"},
{"navn":"losjiEgenBrakkeCampingvogn","term":"Losji egen brakke/campingvogn"},
{"navn":"opsjoner","term":"Opsjoner"},
{"navn":"overtidsgodtgjoerelse","term":"Overtidsgodtgjørelse"},
{"navn":"overtidsmat","term":"Overtidsmat"},
{"navn":"reiseAnnet","term":"Reise annet"},
{"navn":"reiseKost","term":"Reise kost"},
{"navn":"reiseKostMedOvernattingPaaHotell","term":"Reise kost med overnatting på hotell"},
{"navn":"reiseKostMedOvernattingPaaHotellBeordringUtover28Doegn","term":"Reise kost med overnatting på hotell beordring utover 28 døgn"},
{"navn":"reiseKostMedOvernattingPaaHybelBrakkePrivat","term":"Reise kost med overnatting på hybel/brakke/privat"},
{"navn":"reiseKostMedOvernattingPaaPensjonat","term":"Reise kost med overnatting på pensjonat"},
{"navn":"reiseKostMedOvernattingTilLangtransportsjaafoerForKjoeringIUtlandet","term":"Reise kost med overnatting til langtransportsjåfør for kjøring i utlandet"},
{"navn":"reiseKostUtenOvernatting","term":"Reise kost uten overnatting"},
{"navn":"reiseLosji","term":"Reise losji"},
{"navn":"reiseNattillegg","term":"Reise nattillegg"},
{"navn":"rentefordelLaan","term":"Rentefordel lån"},
{"navn":"skattefriErstatning","term":"Skattefri erstatning"},
{"navn":"skattefrieUtbetalinger","term":"Skattefrie utbetalinger"},
{"navn":"skattepliktigDelForsikringer","term":"Skattepliktig del av visse typer forsikringer"},
{"navn":"sluttvederlag","term":"Sluttvederlag"},
{"navn":"smusstillegg","term":"Smusstillegg"},
{"navn":"stipend","term":"Stipend"},
{"navn":"styrehonorarOgGodtgjoerelseVerv","term":"Styrehonorar og godtgjørelse i forbindelse med verv"},
{"navn":"tilskuddBarnehageplass","term":"Tilskudd barnehageplass"},
{"navn":"timeloenn","term":"Timelønn"},
{"navn":"trekkILoennForFerie","term":"Trekk i lønn for ferie"},
{"navn":"uregelmessigeTilleggKnyttetTilArbeidetTid","term":"Uregelmessige tillegg knyttet til arbeidet tid"},
{"navn":"uregelmessigeTilleggKnyttetTilIkkeArbeidetTid","term":"Uregelmessige tillegg knyttet til ikke- arbeidet tid"},
{"navn":"yrkebilTjenestligbehovKilometer","term":"Yrkebil tjenestligbehov kilometer"},
{"navn":"yrkebilTjenestligbehovListepris","term":"Yrkebil tjenestligbehov listepris"}]
 */
