package no.nav.vtp.ytelse;

public enum YtelseType {
    FORELDREPENGER,
    SVANGERSKAPSPENGER,
    PLEIEPENGER,
    DAGPENGER,
    SYKEPENGER,
    ARBEIDSAVKLARINGSPENGER,
    OMSORGSPENGER,
    OPPLÆRINGSPENGER
}
