name: Bygg pull request

on:
  pull_request_target:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.github/workflows/build.yml'
      - '.github/workflows/promote.yml'
      - '.github/workflows/dispatch.yml'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/dependabot.yml'

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }} # Må ha PAT pga avhengighet til private repo: navikt/legacy-avhengigheter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build
        run: |
          mvn install -e -B -s .github/.m2/settings.xml
      - name: Sonar analyse
        run: |
          mvn jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --settings .github/.m2/settings.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
