name: Bygg pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Brukes ukenummer i cache_key da pomene endrer seg alt for ofte.
      # Alternative key med cache fra forrige uke som blir lagret etterpå under CACHE_KEY.
      - name: Set cache key
        run: |
          echo "::set-env name=CACHE_KEY::$(expr $(date +%V) - 1 + 1)"
          echo "::set-env name=PREVIOUS_CACHE_KEY::$(expr $(date +%V) - 1)"
      - name: Henter maven avhengigheter som er cachet
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.PREVIOUS_CACHE_KEY }}

      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Set build version
        run: |
          echo "::set-env name=BUILD_VERSION::$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)"
      - name: Build
        shell: bash
        run: |
          echo "Building $BUILD_VERSION"
          mvn package --batch-mode --settings ./.m2/settings.xml --file pom.xml -Dchangelist= -Dsha1=-${BUILD_VERSION}
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
