name: Publish release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Create maven .m2 setting
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{"id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}",
              "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }}]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GH_ACCESS_TOKEN}}" }]'
          output_file: settings.xml

      - name: Set up JDK-17 with cache
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.7

      - name: Publish artifacts
        run: |
          mvn -B -s settings.xml versions:set -DnewVersion=${{ github.event.release.tag_name }}
          mvn deploy -s settings.xml -e -B -am -pl model,kontrakter -DtrimStackTrace=false -Dfile.encoding=UTF-8 -DdeployAtEnd=true
