
name: Publish kontrakt
on:
  release:
    types: [published]

jobs:
  build:
    name: Bygg pull-request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Publish artifacts
        shell: bash
        run: |
          mvn versions:set -B -DnewVersion=${NEW_VERSION}
          mvn deploy -e -B -am -pl model,kontrakter -DtrimStackTrace=false -Dfile.encoding=UTF-8 -DdeployAtEnd=true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NEW_VERSION: ${{ github.event.release.tag_name }}
