name: Publish release
on:
  release:
    types: [published]

jobs:
  release:
    name: Feature
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/release-feature.yml@main
    with:
      release-version: ${{ github.event.release.tag_name }}
      mvn-projects: '-am -pl model,kontrakter'
    secrets: inherit
